spring:
  application:
    name: Web-Service
  config:
    activate:
      on-profile: prod
  messages:
    basename: messages
    encoding: UTF-8

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      authClient:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 120s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        ignore-exceptions:
          - ru.stroy1click.common.exception.NotFoundException
          - ru.stroy1click.common.exception.ValidationException
      attributeClient:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 120s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        ignore-exceptions:
          - ru.stroy1click.common.exception.NotFoundException
          - ru.stroy1click.common.exception.ValidationException
      attributeOptionClient:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 120s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        ignore-exceptions:
          - ru.stroy1click.common.exception.NotFoundException
          - ru.stroy1click.common.exception.ValidationException
      productAttributeAssignmentClient:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 120s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        ignore-exceptions:
          - ru.stroy1click.common.exception.NotFoundException
          - ru.stroy1click.common.exception.ValidationException
      userClient:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 120s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        ignore-exceptions:
          - ru.stroy1click.common.exception.NotFoundException
          - ru.stroy1click.common.exception.ValidationException
      categoryClient:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 120s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        ignore-exceptions:
          - ru.stroy1click.common.exception.NotFoundException
          - ru.stroy1click.common.exception.ValidationException
      subcategoryClient:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 120s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        ignore-exceptions:
          - ru.stroy1click.common.exception.NotFoundException
          - ru.stroy1click.common.exception.ValidationException
      productTypeClient:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 120s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        ignore-exceptions:
          - ru.stroy1click.common.exception.NotFoundException
          - ru.stroy1click.common.exception.ValidationException
      productClient:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 120s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        ignore-exceptions:
          - ru.stroy1click.common.exception.NotFoundException
          - ru.stroy1click.common.exception.ValidationException
      confirmationCodeClient:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 120s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        ignore-exceptions:
          - ru.stroy1click.common.exception.NotFoundException
          - ru.stroy1click.common.exception.ValidationException

server:
  servlet:
    session:
      timeout: 336h
  port: 3035

jwt:
  secret: 5367566B5970337336762342342342341139792F4123F452811482B4D6251655468576D5A71347437

url:
  user: https://api.stroy1click.ru/api/v1/users
  auth: https://api.stroy1click.ru/api/v1/auth
  confirmationCode: https://api.stroy1click.ru/api/v1/confirmation-codes
  category: https://api.stroy1click.ru/api/v1/categories
  subcategory: https://api.stroy1click.ru/api/v1/subcategories
  productType: https://api.stroy1click.ru/api/v1/product-types
  product: https://api.stroy1click.ru/api/v1/products
  attribute: https://api.stroy1click.ru/api/v1/attributes
  attributeOption: https://api.stroy1click.ru/api/v1/attribute-options
  productAttributeAssignment: https://api.stroy1click.ru/api/v1/product-attribute-assignments
  catalogStorage: http://stroy1click/api/v1/storage
  order: https://api.stroy1click.ru/api/v1/orders
  search: https://api.stroy1click.ru/api/v1/search
  document: http://api.stroy1click/api/v1/documents
  documentStorage: https://api.stroy1click/api/v1/storage