spring:
  application:
    name: Web-Service
  profiles:
    active: dev
  config:
    import: application-prod.yml
  messages:
    basename: messages
    encoding: UTF-8
  servlet:
    multipart:
      max-request-size: 50MB
      max-file-size: 10MB
      enabled: true

management:
  health:
    circuitbreakers:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

resilience4j:
  circuitbreaker:
    instances:
      authClient:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 120s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        ignore-exceptions:
          - ru.stroy1click.common.exception.NotFoundException
          - ru.stroy1click.common.exception.ValidationException
      attributeClient:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 120s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        ignore-exceptions:
          - ru.stroy1click.common.exception.NotFoundException
          - ru.stroy1click.common.exception.ValidationException
      attributeOptionClient:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 120s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        ignore-exceptions:
          - ru.stroy1click.common.exception.NotFoundException
          - ru.stroy1click.common.exception.ValidationException
      productAttributeAssignmentClient:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 120s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        ignore-exceptions:
          - ru.stroy1click.common.exception.NotFoundException
          - ru.stroy1click.common.exception.ValidationException
      userClient:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 120s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        ignore-exceptions:
          - ru.stroy1click.common.exception.NotFoundException
          - ru.stroy1click.common.exception.ValidationException
      categoryClient:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 120s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        ignore-exceptions:
          - ru.stroy1click.common.exception.NotFoundException
          - ru.stroy1click.common.exception.ValidationException
      subcategoryClient:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 120s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        ignore-exceptions:
          - ru.stroy1click.common.exception.NotFoundException
          - ru.stroy1click.common.exception.ValidationException
      productTypeClient:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 120s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        ignore-exceptions:
          - ru.stroy1click.common.exception.NotFoundException
          - ru.stroy1click.common.exception.ValidationException
      productClient:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 120s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        ignore-exceptions:
          - ru.stroy1click.common.exception.NotFoundException
          - ru.stroy1click.common.exception.ValidationException
      confirmationCodeClient:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 120s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        ignore-exceptions:
          - ru.stroy1click.common.exception.NotFoundException
          - ru.stroy1click.common.exception.ValidationException
      searchClient:
        registerHealthIndicator: true
        slidingWindowType: COUNT_BASED
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        failureRateThreshold: 50
        waitDurationInOpenState: 120s
        permittedNumberOfCallsInHalfOpenState: 3
        automaticTransitionFromOpenToHalfOpenEnabled: true
        ignore-exceptions:
          - ru.stroy1click.common.exception.NotFoundException
          - ru.stroy1click.common.exception.ValidationException

server:
  servlet:
    session:
      timeout: 336h
  port: 3035

jwt:
  secret: 5367566B5970337336762342342342341139792F4123F452811482B4D6251655468576D5A71347437

url:
  user: http://localhost:8080/api/v1/users
  auth: http://localhost:9070/api/v1/auth
  token: http://localhost:9070/api/v1/tokens
  confirmationCode: http://localhost:6060/api/v1/confirmation-codes
  category: http://localhost:7070/api/v1/categories
  subcategory: http://localhost:7070/api/v1/subcategories
  productType: http://localhost:7070/api/v1/product-types
  product: http://localhost:7070/api/v1/products
  attribute: http://localhost:4040/api/v1/attributes
  attributeOption: http://localhost:4040/api/v1/attribute-options
  productAttributeAssignment: http://localhost:4040/api/v1/product-attribute-assignments
  catalogStorage: http://localhost:7070/api/v1/storage
  order: http://localhost:1010/api/v1/orders
  notification: http://localhost:2020/api/v1/notifications
  search: http://localhost:4045/api/v1/search
  document: http://localhost:6065/api/v1/documents
  documentStorage: http://localhost:6065/api/v1/storage